#pragma once
#include <Arduino.h>
static const char kWebPage[] PROGMEM=R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Elevator door</title><style>
:root{color-scheme:dark}body{font:16px system-ui;margin:auto;max-width:1050px;padding:24px;background:#121a21;color:#e7edf3}h1{margin-bottom:6px}fieldset{border:1px solid #52606d;border-radius:8px;margin:18px 0;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}label{display:flex;flex-direction:column;gap:6px}input{font:inherit;padding:8px;border:1px solid #728090;border-radius:4px;background:#1d2935;color:inherit}label.check{flex-direction:row;align-items:center}button{font:inherit;padding:10px 18px;border-radius:5px;border:0;margin:5px;background:#8fd8d0;color:#15262a;cursor:pointer}pre{white-space:pre-wrap;word-break:break-word;background:#1d2935;padding:16px;border-radius:8px}#message{min-height:24px;color:#ffc76e}.hint{color:#b5c4d1;font-size:14px}.event{display:grid;grid-template-columns:180px 1fr;gap:12px;margin:10px 0}details{margin:12px 0}
</style></head><body><h1 id="name">Elevator door</h1><p class="hint">Ethernet · USB firmware updates · Local door control</p>
<pre id="status">Loading controller status…</pre><button id="open" type="button">Open door (test)</button><button id="reset" type="button">Reset fault</button><p class="hint">Test open uses the normal door cycle and configured QLab cues. Position must be confirmed and faults cleared. Fault reset does not move the door; manually close it to confirm position before another opening.</p>
<p id="message" role="status"></p><form id="settings">
<fieldset><legend>Ethernet</legend><p>Automatic IP address (DHCP). The current address appears in the status above.</p><p class="hint">USB command: network-reset requests a fresh DHCP lease. Use a DHCP reservation on your network if QLab needs a stable controller address.</p></fieldset>
<fieldset><legend>QLab 5</legend><label class="check"><input type="checkbox" id="qlabEnabled"> Enable cue triggers</label><div class="grid" id="qlab"></div><p class="hint">Enable cue triggers above as well as the desired event below, then save. Leave Workspace ID blank to target all open workspaces listening on the configured port. To target one workspace, copy its unique ID from QLab’s Workspace Status window → Info (for example, 1B11984A-3EBC-4A9C-A004-B9E3AA32DA6B). Use a passcode with control permission if required. Closed is the only event retained during a disconnect. Its cue must tolerate repeated starts.</p></fieldset>
<fieldset><legend>Door event → QLab cue number</legend><div id="events"></div><p class="hint">One cue per event. Map to a QLab Group for multiple actions. Boot/manual position confirmation does not trigger closed.</p></fieldset>
<fieldset><legend>Motion tuning</legend><p class="hint">Fixed scale: 200 motor steps/revolution × 8 microsteps; 600 encoder counts/revolution. Tune only while closed and the motor is released. Electrical and mechanical limits still depend on your hardware.</p><div class="grid" id="motion"></div></fieldset>
<button type="submit">Save configuration</button><button type="button" id="reload">Reload saved settings</button></form>
<details><summary>Raw diagnostics</summary><pre id="raw"></pre></details>
<script>
'use strict';let config;const el=id=>document.getElementById(id);const labels={
travel:'Open travel (microsteps)',openSpeed:'Opening speed (steps / 10,000 s)',reopenSpeed:'Reopening speed (steps / 10,000 s)',closeSpeed:'Closing speed (steps / 10,000 s)',homingSpeed:'Homing speed magnitude (steps / 10,000 s)',
openAccel:'Opening acceleration (steps/s² × 100)',openDecel:'Opening deceleration (steps/s² × 100)',closeAccel:'Closing acceleration (steps/s² × 100)',closeDecel:'Closing deceleration (steps/s² × 100)',homingAccel:'Homing acceleration (steps/s² × 100)',homingDecel:'Homing deceleration (steps/s² × 100)',
openCurrent:'Opening coil current (mA)',closeCurrent:'Closing coil current (mA)',homingCurrent:'Homing coil current (mA)',dwellMs:'Normal dwell (ms)',shortDwellMs:'Short dwell (ms)',settleMs:'Motor settle time (ms)',openTimeoutMs:'Opening deadline (ms)',closeTimeoutMs:'Closing deadline (ms)',homingTimeoutMs:'Homing deadline (ms)',closeDrift:'Closing obstruction threshold (microsteps)',openDrift:'Opening obstruction threshold (microsteps)',
openRetryLimit:'Opening retry limit (0–10)',openRetryDivisor:'Retry speed/acceleration divisor (1–10)',openRetryPauseMs:'Released pause before retry (ms)',openCompletionTolerance:'Open completion tolerance (microsteps, ≤5% of travel)',
host:'QLab host / IPv4 address',port:'QLab OSC TCP port',workspace:'Workspace ID (optional)',passcode:'OSC passcode (optional)',closedExpiryMs:'Pending closed event expiry (ms)'};
function input(parent,group,key,value){const label=document.createElement('label');label.textContent=labels[key]||key;const node=document.createElement('input');node.id=group+'_'+key;node.value=value;node.type=typeof value==='number'?'number':key==='passcode'?'password':'text';if(node.type==='number'){node.step='1';node.min='0'}if(key!=='passcode'&&key!=='workspace'&&key!=='host')node.required=true;label.append(node);parent.append(label)}
async function api(path,options){const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data}
async function load(){try{config=await api('/api/config');el('qlabEnabled').checked=config.qlab.enabled;for(const group of ['qlab','motion']){el(group).replaceChildren();for(const [key,value]of Object.entries(config[group]))if(typeof value!=='boolean'&&key!=='events')input(el(group),group,key,value)}el('events').replaceChildren();for(const [event,mapping]of Object.entries(config.qlab.events)){const row=document.createElement('div');row.className='event';const label=document.createElement('label');label.className='check';const enabled=document.createElement('input');enabled.type='checkbox';enabled.id='event_'+event;enabled.checked=mapping.enabled;label.append(enabled,document.createTextNode(event));row.append(label);const cue=document.createElement('input');cue.id='cue_'+event;cue.value=mapping.cue;cue.placeholder='Cue number';row.append(cue);if(event==='beam_break'){const note=document.createElement('p');note.className='hint';note.style.gridColumn='1 / -1';note.textContent='Beam break fires once per new obstruction, only before the door first initializes after power-up. It is disabled during faults and after initialization until reboot.';row.append(note)}el('events').append(row)}el('message').textContent='Settings loaded.'}catch(e){el('message').textContent=e.message}}
el('settings').onsubmit=async event=>{event.preventDefault();try{const next=structuredClone(config);next.qlab.enabled=el('qlabEnabled').checked;for(const group of ['qlab','motion'])for(const [key,value]of Object.entries(next[group]))if(typeof value!=='boolean'&&key!=='events'){const text=el(group+'_'+key).value;next[group][key]=typeof value==='number'?Number(text):key==='passcode'?text:text.trim()}for(const event of Object.keys(next.qlab.events))next.qlab.events[event]={enabled:el('event_'+event).checked,cue:el('cue_'+event).value.trim()};el('message').textContent='Saving…';await api('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});config=next;el('message').textContent='Settings saved.'}catch(e){el('message').textContent=e.message}};
el('reload').onclick=load;el('reset').onclick=async()=>{try{await api('/api/fault/reset',{method:'POST'});el('message').textContent='Reset requested. Confirm the door is closed.'}catch(e){el('message').textContent=e.message}};
el('open').onclick=async()=>{el('open').disabled=true;try{await api('/api/door/open',{method:'POST'});el('message').textContent='Open requested. Check door status; the controller applies normal position, fault, and command checks.'}catch(e){el('message').textContent=e.message}finally{el('open').disabled=false}};
async function poll(){try{const s=await api('/api/state');el('name').textContent=s.door;el('status').textContent=`Door: ${s.state}   Homed: ${s.homed}   Motor: ${s.energized?'energized':'released'}\nEncoder: ${s.encoderPosition}   Motor position: ${s.motorPosition}\nOpening progress: ${s.encoderPosition}/${s.openingThreshold}   Retries: ${s.openingRetries}/${s.openingRetryLimit} (${s.openingRetryPaused?'paused':s.openingRetryActive?'running':'inactive'})\nClosed cue eligible: ${s.closedCueEligible}\nClosed switch: ${s.limit}   Beam broken: ${s.beam}\nMCP23008: ${s.mcpHealthy?'healthy':'unavailable'}   Buttons up/down: ${s.upButtonPressed}/${s.downButtonPressed}\nEthernet: ${s.ethernet?'connected':'offline'}   IP: ${s.ip}\nQLab: ${s.osc.ready?'ready':s.osc.connected?'setting up':'offline'}\nClosed trigger pending: ${s.pendingClosed}   Age: ${s.pendingAgeMs} ms\nFault: ${s.fault||'none'}   QLab error: ${s.osc.error||'none'}`;el('raw').textContent=JSON.stringify(s,null,2)}catch(e){el('status').textContent='Controller unreachable: '+e.message}setTimeout(poll,500)}load();poll();
</script></body></html>)HTML";
